services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - bridge
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3376/dizplaipoll?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3376:3306
    networks:
      - bridge
    environment:
      MYSQL_DATABASE: dizplaipoll
      MYSQL_USER: newroot
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

networks:
  bridge: